// packages/playground-vue/src/App.vue
<script setup lang="ts">
  const selection = ref(null)
  const darkMode = ref<boolean>(false)
  const clearable = ref<boolean>(false)
  const multipleSelection = ref<boolean>(false)
  const selectedLibraries = ref<string[]>(['tabler'])
  const inputSize = ref<'small' | 'medium' | 'large'>('medium')

  // Iconify collection prefixes - see https://icon-sets.iconify.design for the full list.
  const iconLibraries = [
    'ant-design',
    'carbon',
    'fa',
    'fluent',
    'ion',
    'material-symbols',
    'tabler',
  ]

  const isSelected = (lib: string) => {
    return selectedLibraries.value.find((l: string) => l == lib)
  }

  const toggleSelectedLibraries = (lib: string) => {
    const index = selectedLibraries.value.findIndex((l: string) => l == lib)

    if (index > -1) {
      selectedLibraries.value.splice(index, 1)
    } else {
      selectedLibraries.value.push(lib)
    }
  }

  const toggleMultipleSelection = () => {
    selection.value = null
    multipleSelection.value = !multipleSelection.value

    if (multipleSelection.value) clearable.value = false
  }

  const toggleDarkMode = () => {
    darkMode.value = !darkMode.value
  }

  const toggleClearable = () => {
    if (multipleSelection.value) return
    clearable.value = !clearable.value
  }
</script>

<template>
  <section class="container">
    <h2>D E M O</h2>
    <h4>Icon libraries to display</h4>
    <div class="buttons">
      <div
        v-for="(lib, i) in iconLibraries"
        :key="i"
        class="button"
        :class="{ selected: isSelected(lib) }"
        @click="toggleSelectedLibraries(lib)">
        {{ lib }}
      </div>
    </div>
    <h4>Input sizes</h4>
    <div class="buttons">
      <div
        class="button"
        :class="{ selected: inputSize == 'small' }"
        @click="inputSize = 'small'">
        Small
      </div>
      <div
        class="button"
        :class="{ selected: inputSize == 'medium' }"
        @click="inputSize = 'medium'">
        Medium
      </div>
      <div
        class="button"
        :class="{ selected: inputSize == 'large' }"
        @click="inputSize = 'large'">
        Large
      </div>
    </div>
    <h4>Other options</h4>
    <div class="buttons">
      <div
        class="button"
        :class="{ selected: multipleSelection }"
        @click="toggleMultipleSelection()">
        Multiple selection
      </div>
      <div
        class="button"
        :class="{ selected: darkMode }"
        @click="toggleDarkMode()">
        Dark mode
      </div>
      <div
        class="button"
        :class="{ selected: clearable, disabled: multipleSelection }"
        @click="toggleClearable()">
        Make clearable
      </div>
    </div>
    <hr />
    <Vue3IconPicker
      v-model="selection"
      :icon-library="selectedLibraries"
      :multiple="multipleSelection"
      :clearable="clearable"
      selected-icon-bg-color="#6495ED"
      selected-icon-color="white"
      placeholder="Select icon(s)"
      style="width: 350px; margin-top: 15px"
      :input-size="inputSize"
      :theme="darkMode ? 'dark' : 'light'" />
  </section>
</template>

<style>
  html,
  body {
    width: 100%;
    height: 100%;
    display: flex;
    justify-content: center;
    box-sizing: border-box;
    padding-top: 10px;
    font-family: Georgia, 'Times New Roman', Times, sans-serif;
  }

  .container {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .buttons {
    display: flex;
    align-items: center;
    justify-content: space-around;
    margin-bottom: 5px;
  }

  .button {
    border: 1px solid #ccc;
    padding: 5px 15px;
    cursor: pointer;
    margin-right: 10px;
    margin-left: 10px;
  }

  .selected {
    border: 1px solid #6495ed;
    background-color: #6495ed;
    color: white;
  }

  .disabled {
    cursor: not-allowed;
    opacity: 0.5;
  }
</style>

// packages/playground-react/src/App.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
import React, { useState } from 'react'
import { IconPicker } from '@arkn/react-icon-picker'
import './App.css'

// Iconify collection prefixes - see https://icon-sets.iconify.design for the full list.
const ICON_LIBRARIES = [
  'ant-design', 'carbon', 'fa', 'fluent',
  'ion', 'material-symbols', 'tabler'
]

type InputSize = 'small' | 'medium' | 'large'

const App: React.FC = () => {
  // States
  const [selection, setSelection] = useState<any>(null)
  const [darkMode, setDarkMode] = useState<boolean>(false)
  const [clearable, setClearable] = useState<boolean>(false)
  const [multipleSelection, setMultipleSelection] = useState<boolean>(false)
  const [selectedLibraries, setSelectedLibraries] = useState<string[]>(['tabler'])
  const [inputSize, setInputSize] = useState<InputSize>('medium')

  // Logique métier
  const isSelected = (lib: string) => selectedLibraries.includes(lib)

  const toggleSelectedLibraries = (lib: string) => {
    setSelectedLibraries(prev =>
      prev.includes(lib)
        ? prev.filter(l => l !== lib)
        : [...prev, lib]
    )
  }

  const toggleMultipleSelection = () => {
    setSelection(null)
    setMultipleSelection(!multipleSelection)
    if (!multipleSelection) {
      setClearable(false)
    }
  }

  const toggleDarkMode = () => setDarkMode(!darkMode)

  const toggleClearable = () => {
    if (multipleSelection) return
    setClearable(!clearable)
  }

  return (
    <section className="container">
      <h2>D E M O</h2>

      <h4>Icon libraries to display</h4>
      <div className="buttons">
        {ICON_LIBRARIES.map((lib) => (
          <div
            key={lib}
            className={`button ${isSelected(lib) ? 'selected' : ''}`}
            onClick={() => toggleSelectedLibraries(lib)}>
            {lib}
          </div>
        ))}
      </div>

      <h4>Input sizes</h4>
      <div className="buttons">
        {(['small', 'medium', 'large'] as InputSize[]).map((size) => (
          <div
            key={size}
            className={`button ${inputSize === size ? 'selected' : ''}`}
            onClick={() => setInputSize(size)}>
            {size.charAt(0).toUpperCase() + size.slice(1)}
          </div>
        ))}
      </div>

      <h4>Other options</h4>
      <div className="buttons">
        <div
          className={`button ${multipleSelection ? 'selected' : ''}`}
          onClick={toggleMultipleSelection}>
          Multiple selection
        </div>
        <div
          className={`button ${darkMode ? 'selected' : ''}`}
          onClick={toggleDarkMode}>
          Dark mode
        </div>
        <div
          className={`button ${clearable ? 'selected' : ''} ${multipleSelection ? 'disabled' : ''}`}
          onClick={toggleClearable}>
          Make clearable
        </div>
      </div>

      <hr />

      <IconPicker
        value={selection}
        onChange={setSelection}
        iconLibrary={selectedLibraries}
        multiple={multipleSelection}
        clearable={clearable}
        selectedIconBgColor="#6495ED"
        selectedIconColor="white"
        placeholder="Select icon(s)"
        style={{ width: '350px', marginTop: '15px' }}
        inputSize={inputSize}
        theme={darkMode ? 'dark' : 'light'}
      />
    </section>
  )
}

export default App
